### ISSUE TITLE
Training udify model for Russian.

### ISSUE THREAD

**Issue by Aditi138** [Hyperparticle/udify#21]
Hello, I am training a udify model only for Russian where I train only on the Russian data from UD2.3. However, I am running into the following issue. The same code runs fine on other languages from UD. 
Traceback (most recent call last):
  File "train.py", line 69, in <module>
    train_model(train_params, serialization_dir, recover=bool(args.resume))
  File "/usr1/home/user/anaconda2/envs/py36/lib/python3.6/site-packages/allennlp/commands/train.py", line 226, in train_model
    cache_prefix)
  File "/usr1/home/user/anaconda2/envs/py36/lib/python3.6/site-packages/allennlp/training/trainer_pieces.py", line 65, in from_params
    model = Model.from_params(vocab=vocab, params=params.pop('model'))
  File "/usr1/home/user/anaconda2/envs/py36/lib/python3.6/site-packages/allennlp/common/from_params.py", line 365, in from_params
    return subclass.from_params(params=params, **extras)
  File "/usr1/home/user/anaconda2/envs/py36/lib/python3.6/site-packages/allennlp/common/from_params.py", line 386, in from_params
    kwargs = create_kwargs(cls, params, **extras)
  File "/usr1/home/user/anaconda2/envs/py36/lib/python3.6/site-packages/allennlp/common/from_params.py", line 133, in create_kwargs
    kwargs[name] = construct_arg(cls, name, annotation, param.default, params, **extras)
  File "/usr1/home/user/anaconda2/envs/py36/lib/python3.6/site-packages/allennlp/common/from_params.py", line 257, in construct_arg
    value_dict[key] = value_cls.from_params(params=value_params, **subextras)
  File "/usr1/home/user/anaconda2/envs/py36/lib/python3.6/site-packages/allennlp/common/from_params.py", line 365, in from_params
    return subclass.from_params(params=params, **extras)
  File "/usr1/home/user/anaconda2/envs/py36/lib/python3.6/site-packages/allennlp/common/from_params.py", line 388, in from_params
    return cls(**kwargs)  # type: ignore
  File "/usr1/home/user/udify/udify/models/tag_decoder.py", line 106, in __init__
    div_value=4.0)
  File "/usr1/home/user/anaconda2/envs/py36/lib/python3.6/site-packages/torch/nn/modules/adaptive.py", line 116, in __init__
    raise ValueError("cutoffs should be a sequence of unique, positive "
ValueError: cutoffs should be a sequence of unique, positive integers sorted in an increasing order, where each value is between 1 and n_classes-1

**Comment by Hyperparticle** [comment]
Were you able to solve the issue?

**Comment by Aditi138** [comment]
Yes, I was able to!

**Comment by euhkim** [comment]
> Yes, I was able to!

How did you solve it?
